# Generated by Django 5.0.6 on 2024-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_sub_category_category_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
